name: graphql_flutter_bloc_example
description: A new Flutter project.

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql:
    path: ../../packages/graphql
  graphql_flutter_bloc: ^0.4.4-beta.1
  cupertino_icons: ^0.1.2
  flutter_bloc: ^6.0.5
  freezed_annotation: 0.12.0
  path_provider: ^1.6.18
  hive: ^1.4.4
  equatable: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0
  mockito: ^3.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  graphql:
    path: ../../packages/graphql
    
