name: app
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  graphql_flutter:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

flutter:
  uses-material-design: true
