name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 1.0.0-beta.1+1
authors:
  - Eus Dima <eus@zinoapp.com>
  - Zino Hofmann <zino@zinoapp.com>
homepage: https://github.com/zino-app/graphql-flutter/tree/next

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  http: ^0.12.0
  mime: 0.9.6+2
  http_parser: ^3.1.3
  path_provider: ^0.5.0
  uuid: ^2.0.0
  graphql_parser: ^1.1.1

dev_dependencies:
  perfectionist: ^2.0.0
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.3.0

environment:
  sdk: ">=2.0.0 <3.0.0"
