name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 0.9.5
authors:
  - Eus Dima <eus@zinoapp.com>
  - Zino Hofmann <zino@zinoapp.com>
homepage: https://github.com/zino-app/graphql-flutter

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  path_provider: ^0.4.1
  uuid: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0

environment:
  sdk: ">=2.0.0 <3.0.0"
