name: graphql_flutter
description: A GraphQL client for Flutter.
version: 0.7.0
authors:
- Eus Dima <eus@zinoapp.com>
- Zino Hofmann <zino@zinoapp.com>
homepage: https://github.com/zino-app/graphql-flutter

dependencies:
  flutter:
    sdk: flutter
  http: ^0.11.0
  path_provider: ^0.4.0
  uuid: ^1.0.1
  test: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: ">=2.0.0-dev.52.0"