name: app
description: A new Flutter project.

module:
  androidX: true // Add this line.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  rxdart: ^0.22.0
  connectivity: ^0.4.4
  graphql_flutter:
    path: ..

dev_dependencies:
  pedantic: ^1.8.0+1
  flutter_test:
    sdk: flutter
  test: ^1.5.1

flutter:
  uses-material-design: true
