name: app
description: A new Flutter project.

publish_to: none

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  graphql_flutter:
    path: ..
  trash_themes: ^0.0.1

dev_dependencies:
  pedantic: ^1.8.0+1
  flutter_test:
    sdk: flutter
  test: ^1.17.12

flutter:
  uses-material-design: true

dependency_overrides:
  graphql:
    path: ../../graphql

environment:
  sdk: '>=2.12.0 <3.0.0'
