name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.0.0-beta.2
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql
dependencies:
  meta: ^1.3.0
  path: ^1.8.0
  gql: ^0.13.0
  gql_exec: ^0.3.0
  gql_link: ^0.4.0
  gql_http_link: ^0.4.0
  gql_transform_link: ^0.2.0
  gql_error_link: ^0.2.0
  gql_dedupe_link: ^2.0.0
  hive: ^2.0.0
  normalize: ^0.5.3
  http: ^0.13.0
  collection: ^1.15.0
  web_socket_channel: ^2.0.0
  stream_channel: ^2.1.0
  rxdart: ^0.26.0
  uuid: ^3.0.1
dev_dependencies:
  async: ^2.5.0
  pedantic: ^1.8.0+1
  mockito: ^5.0.0
  test: ^1.5.3
  http_parser: ^4.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'
