name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from
  a modern GraphQL client to one easy to use package.
version: 2.0.0
authors:
- Eus Dima <eus@zinoapp.com>
- Zino Hofmann <zino@zinoapp.com>
- Michael Joseph Rosenthal <rosenthalm93@gmail.com>
- TruongSinh Tran-Nguyen <i@truongsinh.pro>
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql
dependencies:
  meta: ^1.1.6
  http: ^0.12.0+2
  mime: ^0.9.6+2
  path: ^1.6.2
  http_parser: ^3.1.3
  uuid_enhanced: ^3.0.2
  graphql_parser: ^1.1.3
  rxdart: ^0.22.0
  websocket: ^0.0.5
dev_dependencies:
  pedantic: <=1.7.99
  mockito: ^4.0.0
  test: ^1.5.3
  test_coverage: ^0.2.0
environment:
  sdk: '>=2.2.0 <3.0.0'
