name: graphql
description: A stand-alone GraphQL client for Dart, bringing all the features from a modern GraphQL client to one easy to use package.
version: 4.1.0-beta.2
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql
dependencies:
  meta: ^1.3.0
  path: ^1.8.0
  gql: ^0.13.0-nullsafety.2
  gql_exec: ^0.3.0-nullsafety.1
  gql_link: ^0.4.0-nullsafety.1
  gql_http_link: ^0.4.0-nullsafety.1
  gql_transform_link: ^0.2.0-nullsafety.1
  gql_error_link: ^0.2.0-nullsafety.1
  gql_dedupe_link: ^2.0.0-nullsafety.1
  hive: ^1.3.0
  normalize: ^0.5.0-nullsafety.0
  http: ^0.13.0
  collection: ^1.14.12
  web_socket_channel: ^2.0.0
  rxdart: ^0.26.0
  uuid: ^3.0.1
dev_dependencies:
  async: ^2.5.0
  pedantic: ^1.8.0+1
  mockito: ^4.0.0
  test: ^1.5.3
  test_coverage: ^0.5.0
  http_parser: ^4.0.0
environment:
  sdk: '>=2.10.0 <3.0.0'
