name: graphql
description:
  A stand-alone GraphQL client for Dart, bringing all the features from
  a modern GraphQL client to one easy to use package.
version: 4.0.0-alpha.0
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql
dependencies:
  meta: ^1.1.6
  path: ^1.6.2

  gql: ^0.12.0
  gql_exec: ^0.2.2
  gql_link: ^0.3.0
  gql_http_link: ^0.2.9
  gql_websocket_link: ^0.1.1-alpha
  gql_transform_link: ^0.1.5
  gql_error_link:  ^0.1.1-alpha
  gql_dedupe_link: ^1.0.10

  hive: ^1.3.0
  normalize: ^0.2.0
  http: ^0.12.1
  collection: ^1.14.12


dev_dependencies:
  pedantic: ^1.8.0+1
  mockito: ^4.0.0
  test: ^1.5.3
  test_coverage: ^0.3.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

