name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.0.1-beta.1
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter
publish_to: none
dependencies:
  graphql: # 5.0.0
    path: ../graphql
  gql_exec: ^0.3.0
  flutter:
    sdk: flutter
  meta: ^1.3.0
  path_provider: ^2.0.1
  path: ^1.8.0
  connectivity_plus: ^2.0.3
  hive: ^2.0.0
  plugin_platform_interface: ^2.0.0
dev_dependencies:
  pedantic: ^1.11.0
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter
  http: ^0.13.0
environment:
  sdk: '>=2.12.0 <3.0.0'
