name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 5.2.0-beta.6
repository: https://github.com/zino-app/graphql-flutter/tree/main/packages/graphql_flutter
issue_tracker: https://github.com/zino-hofmann/graphql-flutter/issues

# just for dev work
# publish_to: 'none'

dependencies:
  graphql: ^5.2.0-beta.4
  gql_exec: ^1.0.0
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path_provider: ^2.0.1
  path: ^1.8.0
  connectivity_plus: ^6.0.1
  hive: ^2.0.0
  plugin_platform_interface: ^2.0.0
  flutter_hooks: '>=0.18.2 <0.21.0'

dev_dependencies:
  pedantic: ^1.11.0
  mockito: ^5.0.0
  flutter_test:
    sdk: flutter
  http: ^1.0.0
  test: ^1.17.12

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.11.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
