name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 1.0.1-beta
authors:
  - Eus Dima <eus@zinoapp.com>
  - Zino Hofmann <zino@zinoapp.com>
  - Michael Joseph Rosenthal <rosenthalm93@gmail.com>

homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter

dependencies:
  graphql: ^1.0.1-beta # path: ../graphql
  flutter:
    sdk: flutter
  meta: ^1.1.6
  path: ^1.6.2
  path_provider: ^0.5.0+1
  rxdart: ^0.21.0

dev_dependencies:
  perfectionist: ^2.0.0
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
  test: ^1.5.3

environment:
  sdk: ">=2.2.0 <3.0.0"
