name: graphql_flutter
description: A GraphQL client for Flutter, bringing all the features from a modern GraphQL client to one easy to use package.
version: 4.1.0-beta.1
homepage: https://github.com/zino-app/graphql-flutter/tree/master/packages/graphql_flutter
dependencies:
  graphql: ^4.1.0-beta.1
  gql_exec: ^0.3.0-nullsafety.1
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  path_provider: ^1.6.10
  path: ^1.8.0
  connectivity: ^3.0.2
  hive: ^1.3.0
dev_dependencies:
  pedantic: ^1.11.0
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
  http: ^0.13.0
environment:
  sdk: '>=2.10.0 <3.0.0'
