name: starwars_server

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  graphql_starwars_test_server: ^0.1.0

dependency_overrides:
  graphql_server:
    git:
      url: git@github.com:micimize/angel.git
      ref: typeerror2.8-fix
      path: packages/graphql/graphql_server
  graphql_parser:
    git:
      url: git@github.com:micimize/angel.git
      path: packages/graphql/graphql_parser
